### ISSUE TITLE
Breaks a lot of commands

### ISSUE THREAD

**Issue by nv05hndi1306** [KDot227/Somalifuscator-Powershell-Edition#1]
This looks sick, respect! But it sadly destroys a lot of commands, which make the code kind of unusable. Is it normal?

**Comment by KDot227** [comment]
> This looks sick, respect! But it sadly destroys a lot of commands, which make the code kind of unusable. Is it normal?

Can you provide any instances of code which don't work?

**Comment by nv05hndi1306** [comment]
> > This looks sick, respect! But it sadly destroys a lot of commands, which make the code kind of unusable. Is it normal?
> 
> Can you provide any instances of code which don't work?

If writing Write-Host "" the prompt will show [string]::Empty. Variables like $host or $null dont work anymore, switching between functions is buggy/sometimes doesnt work.

Something like this also doesnt work anymore

    for ($i = 35; $i -le 75; $i++) {
        Write-Host -NoNewline "`r Downloading "
        Write-Host -NoNewline "preset" -ForegroundColor Cyan
        Write-Host -NoNewline ", please wait ["
        Write-Host -NoNewline "$i%" -ForegroundColor Red
        Write-Host -NoNewline "]"
        Start-Sleep -Milliseconds 20
    }
    
 
  and more visual bugs

**Comment by KDot227** [comment]
> > > This looks sick, respect! But it sadly destroys a lot of commands, which make the code kind of unusable. Is it normal?
> > 
> > 
> > Can you provide any instances of code which don't work?
> 
> If writing Write-Host "" the prompt will show [string]::Empty. Variables like $host or $null dont work anymore, switching between functions is buggy/sometimes dont work (either takes 1-3 seconds to instantly skips a function ->2nd function has for example $null = $host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") at the end so it doesnt stop, it just instantly "skips" it, as $null doesnt work)
> 
> Something like this also doesnt work anymore
> 
> ```
> for ($i = 35; $i -le 75; $i++) {
>     Write-Host -NoNewline "`r Downloading "
>     Write-Host -NoNewline "preset" -ForegroundColor Cyan
>     Write-Host -NoNewline ", please wait ["
>     Write-Host -NoNewline "$i%" -ForegroundColor Red
>     Write-Host -NoNewline "]"
>     Start-Sleep -Milliseconds 20
> }
> ```
> 
> and more visual bugs

I see. I'm fixing right now

**Comment by KDot227** [comment]
Issue is now fixed with that code. If you encounter any more issues please lmk.

**Comment by nv05hndi1306** [comment]
> Issue is now fixed with that code. If you encounter any more issues please lmk.

Still the same issues, $host doesnt work, but it could be replaced, $null also doesnt work and it still shows [string]::Empty, if writing 'Write-Host ""'

**Comment by nv05hndi1306** [comment]
> Issue is now fixed with that code. If you encounter any more issues please lmk.

$env also doesnt work

**Comment by KDot227** [comment]
> > Issue is now fixed with that code. If you encounter any more issues please lmk.
> 
> Still the same issues, $host doesnt work, but it could be replaced, $null also doesnt work and it still shows [string]::Empty, if writing 'Write-Host ""'

I need to add in all global vars to the list. Right now I only have a few. It can be found within the variable obfuscation file. Write-Host returns [string::Empty?

**Comment by nv05hndi1306** [comment]
> > > Issue is now fixed with that code. If you encounter any more issues please lmk.
> 
> > 
> 
> > Still the same issues, $host doesnt work, but it could be replaced, $null also doesnt work and it still shows [string]::Empty, if writing 'Write-Host ""'
> 
> 
> 
> I need to add in all global vars to the list. Right now I only have a few. It can be found within the variable obfuscation file. Write-Host returns [string::Empty?

Also yes and the other ones I've said

**Comment by KDot227** [comment]
Thank you for the feedback. Both issues should be fixed now.

**Comment by nv05hndi1306** [comment]
> Thank you for the feedback. Both issues should be fixed now.

Nice, it is fixed, but I still found issues (sorry if im annoying ;D)

It duplicates "'", if they're in a write-host message (maybe also outside of these write suff) and if writing Write-Host "'", the script shows [string]::Empty, seems like it handles this ' incorrectly anywhere

**Comment by nv05hndi1306** [comment]
![IMG_1328](https://github.com/user-attachments/assets/5569ddd5-f3fe-4f85-871c-13c22611af3b)
it also shows this

**Comment by KDot227** [comment]
> ![IMG_1328](https://private-user-images.githubusercontent.com/177646984/391267409-5569ddd5-f3fe-4f85-871c-13c22611af3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMDMzNjIsIm5iZiI6MTczMzAwMzA2MiwicGF0aCI6Ii8xNzc2NDY5ODQvMzkxMjY3NDA5LTU1NjlkZGQ1LWYzZmUtNGY4NS04NzFjLTEzYzIyNjExYWYzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQyMTQ0MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzFhNDg5ZDUzNzFlZmJiYmNlYzNkNTQ4NWY0ZjJmOTAwZWQ4ZjY1NjE1YWVkMGUwOTgxM2ZjNjkzYzAwYWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jTaQOWDXZOwLaPwM78V0EJJKK3-BOpxgXKT4vtlM70M) it also shows this

What was the code before obfuscation?

**Comment by nv05hndi1306** [comment]
but idk why it duplicates the '

**Comment by nv05hndi1306** [comment]
> > but idk why it duplicates the ' and shows [string]::Empty, if writing Write-Host "'"
> 
> It's because I just didn't make a good enough check for it. I'll fix that today too thank you.

Is it already changed?

**Comment by nv05hndi1306** [comment]
Hi,
$string = $string -replace "`'", "`'`'"
is causing the dublication of ' in outputs and it also causes the Write-Host "'" to show [string]::Empty

**Comment by KDot227** [comment]
> Hi, $string = $string -replace "`'", "`'`'" is causing the dublication of ' in outputs and it also causes the Write-Host "'" to show [string]::Empty .Somalifuscator-Powershell-Edition\util\strings\strings.ps1 - line 15

That's very annoying. I will try and fix it tomorrow.

**Comment by nv05hndi1306** [comment]
Maybe also add $global: to the variable starts
